#!/usr/bin/env python3
"""Decode an MP3 into raw PCM for the C64 Ultimate's hardware sampler.

    python3 tools/mp3topcm.py "assets/04 - Intermission From Doom.mp3" \
        -o build/intro.reu --asm build/intro-audio.asm

The Ultimate Audio module (register API pulled into src/intro/ultaudio.asm)
plays 8-bit unsigned PCM straight out of REU memory -- no player code, no
CPU time per sample, just an address, a length and a divider register. So
the whole job here is offline: decode the mp3 and resample it, then hand the
raw bytes to the REU image the Ultimate's sampler reads from directly. There
is no on-C64 decoding step at all, unlike tools/sidstream.py's SID register
capture -- PCM needs no player to interpret it, only a DAC.

Needs ffmpeg on PATH (decode only; nothing here parses the mp3 container
itself).

Output is **mono**: 3.6 MB for the 2:53 track instead of stereo's 7.6 MB, for
a difference nobody hears on a title screen. The sampler's two channels play
the same buffer panned hard left and right, so its "interleave" control bit --
which lets two channels share one stereo buffer a byte apart -- is not used
here at all.

Nothing pushes this image over the network. It is loaded once from the
Ultimate's own menu (REU Preload Image -> /Usb0/intro.reu, then reset) and
stays in REU RAM across resets; docs/reu-format.md §9.2 has the history,
including why the project believed for a while that preload did not work.
Reload it by hand after re-running this program.

The REU image is padded to REU_SIZE because VICE's -reuimage demands an exact
match to -reusize (docs/reu-format.md §9.1). Keep REU_SIZE and the Makefile's
-reusize for the intro in step.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys

# 4 MB holds the ~3.6 MB mono track with room to spare, and is a size VICE's
# -reusize offers. The Ultimate's own REU Size stays at 16 MB -- it costs
# nothing there, the engine already runs with it, and nothing about the upload
# path measures differently at one size or another.
REU_SIZE = 4 * 1024 * 1024

# The sampler's own reference clock (register API v0.2 §2.4.6): the rate
# register is a divider from a fixed 6.25 MHz, not a Hz value.
DIVIDER_CLOCK = 6_250_000


def decode(mp3: str, rate: int) -> bytes:
    """mp3 -> mono 8-bit unsigned PCM, via ffmpeg.

    -vn drops the embedded cover-art video stream ffprobe reports on these
    files; without it ffmpeg either errors or tries to transcode a JPEG.
    """
    cmd = ["ffmpeg", "-y", "-v", "error", "-i", mp3, "-vn",
           "-ar", str(rate), "-ac", "1", "-f", "u8", "-acodec", "pcm_u8", "-"]
    try:
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, check=True)
    except FileNotFoundError:
        print("error: ffmpeg not found on PATH -- it decodes the mp3; "
              "nothing here does", file=sys.stderr)
        raise SystemExit(2)
    except subprocess.CalledProcessError as exc:
        print(f"error: ffmpeg failed: {exc}", file=sys.stderr)
        raise SystemExit(2)
    return proc.stdout


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("mp3")
    ap.add_argument("-o", "--out", required=True,
                    help="write the padded REU image here")
    ap.add_argument("--asm", required=True,
                    help="write the generated .asm constants here "
                         "(AUDIO_LEN, AUDIO_RATE)")
    ap.add_argument("--rate", type=int, default=22050,
                    help="sample rate in Hz (default 22050 -- ~3.6 MB of "
                         "mono for a 3-minute track; halve it if the upload "
                         "needs to be shorter still)")
    args = ap.parse_args(argv)

    pcm = decode(args.mp3, args.rate)
    if len(pcm) > REU_SIZE:
        print(f"error: {len(pcm)} B of PCM does not fit the {REU_SIZE} B "
              f"REU -- lower --rate", file=sys.stderr)
        return 2

    divider = round(DIVIDER_CLOCK / args.rate)
    actual_rate = DIVIDER_CLOCK / divider
    seconds = len(pcm) / args.rate

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "wb") as fh:
        fh.write(pcm)
        fh.write(bytes(REU_SIZE - len(pcm)))

    os.makedirs(os.path.dirname(args.asm) or ".", exist_ok=True)
    with open(args.asm, "w") as fh:
        fh.write(
            "// Generated by tools/mp3topcm.py from "
            f"{os.path.basename(args.mp3)} -- do not edit.\n"
            f".const AUDIO_LEN  = {len(pcm)}\n"
            f".const AUDIO_RATE = {divider}\n"
        )

    print(f"{args.mp3}")
    print(f"  {seconds:.1f}s mono @ {args.rate} Hz "
          f"(divider {divider} -> {actual_rate:.1f} Hz actual)")
    print(f"  {len(pcm)} B PCM, padded to {REU_SIZE} B -> {args.out}")
    print(f"  -> {args.asm}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
